### ISSUE TITLE
Create custom segmentedControl in "Lines" view controller

### ISSUE THREAD

**Issue by ljuba** [ljuba/Transporter-iPhone#19]
The images used by the segmented control overlap in strange ways because the standard segmentedControl isn't meant to have custom images for each segment. The custom segmentedControl should be a collection of UIButtons and should support any number of buttons.

**Comment by ndlupine** [comment]
In iOS 5+ You can give UISegmentedControl custom images through the Appearance API. I did it for work just a week or two ago, I'd be happy to set it up for Transporter!

**Comment by ljuba** [comment]
Hey. I don't think that part's really necessary anymore. The issue should probably be closed.
