### ISSUE TITLE
Use MKMapView in the Directions view controller instead of static map

### ISSUE THREAD

**Issue by ljuba** [ljuba/Transporter-iPhone#23]
This needs to go along with OTA updates since we don't want to be downloading tons of static map images over 3G. Ideally, the map, once loaded, will be stored in a cache so that next time that bitmap can be shown instead.

**Comment by rodericj** [comment]
Can we assign this to me?

**Comment by ljuba** [comment]
Done

**Comment by ljuba** [comment]
Looks really good. There are only a few small cosmetic issues left.
1. The algorithm you're using to place the pins/callouts isn't taking into account the 10pt inner padding that should surround the map view. i.e. There are routes for which the callout bumps right up against the edge of the map (e.g. [F streetcar](http://imgur.com/XU9An,55k0n#0) and [30X bus](http://imgur.com/XU9An,55k0n#1))
2. There should be a darker "down" state for the callouts. The asset is in the original project folder. 
3. The text in the callouts should be moved down and to the left a bit. (I can do this after I pull it to my branch)

Awesome work. I can't wait to push this and not have to deal with those silly map images anymore!
